"""locomotive maintenance table form was added

Revision ID: 2297a1d87161
Revises: effc0832853d
Create Date: 2021-12-16 17:58:37.307404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2297a1d87161'
down_revision = 'effc0832853d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_model', sa.String(length=10), nullable=False),
    sa.Column('loco_number', sa.String(length=10), nullable=False),
    sa.Column('m3_last', sa.Date(), nullable=True),
    sa.Column('m3_next', sa.Date(), nullable=True),
    sa.Column('cr1_last', sa.Date(), nullable=True),
    sa.Column('cr1_next', sa.Date(), nullable=True),
    sa.Column('cr2_last', sa.Date(), nullable=True),
    sa.Column('cr2_next', sa.Date(), nullable=True),
    sa.Column('cr3_last', sa.Date(), nullable=True),
    sa.Column('cr3_next', sa.Date(), nullable=True),
    sa.Column('mr_last', sa.Date(), nullable=True),
    sa.Column('mr_next', sa.Date(), nullable=True),
    sa.Column('overhaul_last', sa.Date(), nullable=True),
    sa.Column('overhaul_next', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loco_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_register')
    # ### end Alembic commands ###
