"""I added foreign key, renamed variables, added timestamp column.

Revision ID: 555508e02b7b
Revises: a0108b7f8cbb
Create Date: 2021-12-21 08:10:14.686977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555508e02b7b'
down_revision = 'a0108b7f8cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_repair_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_number', sa.String(length=10), nullable=False),
    sa.Column('last_three_maintenance', sa.Date(), nullable=True),
    sa.Column('next_three_maintenance', sa.Date(), nullable=True),
    sa.Column('last_three_current_repair', sa.Date(), nullable=True),
    sa.Column('next_three_current_repair', sa.Date(), nullable=True),
    sa.Column('last_two_current_repair', sa.Date(), nullable=True),
    sa.Column('next_two_current_repair', sa.Date(), nullable=True),
    sa.Column('last_one_current_repair', sa.Date(), nullable=True),
    sa.Column('next_one_current_repair', sa.Date(), nullable=True),
    sa.Column('last_medium_repair', sa.Date(), nullable=True),
    sa.Column('next_medium_repair', sa.Date(), nullable=True),
    sa.Column('last_overhaul', sa.Date(), nullable=True),
    sa.Column('next_overhaul', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_repair_forms_loco_number'), 'saved_repair_forms', ['loco_number'], unique=False)
    op.create_index(op.f('ix_saved_repair_forms_timestamp'), 'saved_repair_forms', ['timestamp'], unique=False)
    op.drop_index('ix_data_store_loco_model', table_name='data_store')
    op.drop_index('ix_data_store_loco_number', table_name='data_store')
    op.drop_table('data_store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_store',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loco_model', sa.VARCHAR(length=10), nullable=False),
    sa.Column('loco_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('m3_last', sa.DATE(), nullable=True),
    sa.Column('m3_next', sa.DATE(), nullable=True),
    sa.Column('cr1_last', sa.DATE(), nullable=True),
    sa.Column('cr1_next', sa.DATE(), nullable=True),
    sa.Column('cr2_last', sa.DATE(), nullable=True),
    sa.Column('cr2_next', sa.DATE(), nullable=True),
    sa.Column('cr3_last', sa.DATE(), nullable=True),
    sa.Column('cr3_next', sa.DATE(), nullable=True),
    sa.Column('mr_last', sa.DATE(), nullable=True),
    sa.Column('mr_next', sa.DATE(), nullable=True),
    sa.Column('overhaul_last', sa.DATE(), nullable=True),
    sa.Column('overhaul_next', sa.DATE(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_store_loco_number', 'data_store', ['loco_number'], unique=False)
    op.create_index('ix_data_store_loco_model', 'data_store', ['loco_model'], unique=False)
    op.drop_index(op.f('ix_saved_repair_forms_timestamp'), table_name='saved_repair_forms')
    op.drop_index(op.f('ix_saved_repair_forms_loco_number'), table_name='saved_repair_forms')
    op.drop_table('saved_repair_forms')
    # ### end Alembic commands ###
