"""Tables initialization

Revision ID: 5c27b8115c46
Revises: 
Create Date: 2022-01-18 11:58:12.190417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c27b8115c46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locomotive_repair_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_model_name', sa.String(length=10), nullable=False),
    sa.Column('three_maintenance', sa.Integer(), nullable=False),
    sa.Column('one_current_repair', sa.Integer(), nullable=False),
    sa.Column('two_current_repair', sa.Integer(), nullable=False),
    sa.Column('three_current_repair', sa.Integer(), nullable=False),
    sa.Column('medium_repair', sa.Integer(), nullable=False),
    sa.Column('overhaul', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locomotive_repair_period_loco_model_name'), 'locomotive_repair_period', ['loco_model_name'], unique=True)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.Column('role_codename', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_role_codename'), 'user_role', ['role_codename'], unique=False)
    op.create_table('saved_repair_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_model_id', sa.Integer(), nullable=True),
    sa.Column('loco_number', sa.String(length=10), nullable=False),
    sa.Column('last_three_maintenance', sa.Date(), nullable=True),
    sa.Column('next_three_maintenance', sa.Date(), nullable=True),
    sa.Column('last_three_current_repair', sa.Date(), nullable=True),
    sa.Column('next_three_current_repair', sa.Date(), nullable=True),
    sa.Column('last_two_current_repair', sa.Date(), nullable=True),
    sa.Column('next_two_current_repair', sa.Date(), nullable=True),
    sa.Column('last_one_current_repair', sa.Date(), nullable=True),
    sa.Column('next_one_current_repair', sa.Date(), nullable=True),
    sa.Column('last_medium_repair', sa.Date(), nullable=True),
    sa.Column('next_medium_repair', sa.Date(), nullable=True),
    sa.Column('last_overhaul', sa.Date(), nullable=True),
    sa.Column('next_overhaul', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loco_model_id'], ['locomotive_repair_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_repair_forms_loco_number'), 'saved_repair_forms', ['loco_number'], unique=False)
    op.create_index(op.f('ix_saved_repair_forms_timestamp'), 'saved_repair_forms', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_saved_repair_forms_timestamp'), table_name='saved_repair_forms')
    op.drop_index(op.f('ix_saved_repair_forms_loco_number'), table_name='saved_repair_forms')
    op.drop_table('saved_repair_forms')
    op.drop_index(op.f('ix_user_role_role_codename'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_locomotive_repair_period_loco_model_name'), table_name='locomotive_repair_period')
    op.drop_table('locomotive_repair_period')
    # ### end Alembic commands ###
