"""empty message

Revision ID: 8cdedfb602e9
Revises: ca2e24e0b1d2
Create Date: 2021-12-31 14:40:34.215282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdedfb602e9'
down_revision = 'ca2e24e0b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_repair_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_model_id', sa.Integer(), nullable=True),
    sa.Column('loco_number', sa.String(length=10), nullable=False),
    sa.Column('last_three_maintenance', sa.Date(), nullable=True),
    sa.Column('next_three_maintenance', sa.Date(), nullable=True),
    sa.Column('last_three_current_repair', sa.Date(), nullable=True),
    sa.Column('next_three_current_repair', sa.Date(), nullable=True),
    sa.Column('last_two_current_repair', sa.Date(), nullable=True),
    sa.Column('next_two_current_repair', sa.Date(), nullable=True),
    sa.Column('last_one_current_repair', sa.Date(), nullable=True),
    sa.Column('next_one_current_repair', sa.Date(), nullable=True),
    sa.Column('last_medium_repair', sa.Date(), nullable=True),
    sa.Column('next_medium_repair', sa.Date(), nullable=True),
    sa.Column('last_overhaul', sa.Date(), nullable=True),
    sa.Column('next_overhaul', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loco_model_id'], ['locomotive_repair_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_repair_forms_loco_number'), 'saved_repair_forms', ['loco_number'], unique=False)
    op.create_index(op.f('ix_saved_repair_forms_timestamp'), 'saved_repair_forms', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_repair_forms_timestamp'), table_name='saved_repair_forms')
    op.drop_index(op.f('ix_saved_repair_forms_loco_number'), table_name='saved_repair_forms')
    op.drop_table('saved_repair_forms')
    # ### end Alembic commands ###
