"""empty message

Revision ID: a0108b7f8cbb
Revises: 2f292aba5180
Create Date: 2021-12-19 18:59:45.562146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0108b7f8cbb'
down_revision = '2f292aba5180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_store_loco_model'), 'data_store', ['loco_model'], unique=False)
    op.create_index(op.f('ix_data_store_loco_number'), 'data_store', ['loco_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_store_loco_number'), table_name='data_store')
    op.drop_index(op.f('ix_data_store_loco_model'), table_name='data_store')
    # ### end Alembic commands ###
