"""empty message

Revision ID: ca2e24e0b1d2
Revises: 7a30400b59f1
Create Date: 2021-12-31 14:24:39.279841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2e24e0b1d2'
down_revision = '7a30400b59f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locomotive_repair_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loco_model_name', sa.String(length=10), nullable=False),
    sa.Column('three_maintenance', sa.Integer(), nullable=False),
    sa.Column('one_current_repair', sa.Integer(), nullable=False),
    sa.Column('two_current_repair', sa.Integer(), nullable=False),
    sa.Column('three_current_repair', sa.Integer(), nullable=False),
    sa.Column('medium_repair', sa.Integer(), nullable=False),
    sa.Column('overhaul', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locomotive_repair_period_loco_model_name'), 'locomotive_repair_period', ['loco_model_name'], unique=True)
    op.drop_index('ix_repair_period_loco_model', table_name='repair_period')
    op.drop_table('repair_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_period',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loco_model_name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('three_maintenance', sa.INTEGER(), nullable=False),
    sa.Column('one_current_repair', sa.INTEGER(), nullable=False),
    sa.Column('two_current_repair', sa.INTEGER(), nullable=False),
    sa.Column('three_current_repair', sa.INTEGER(), nullable=False),
    sa.Column('medium_repair', sa.INTEGER(), nullable=False),
    sa.Column('overhaul', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repair_period_loco_model', 'repair_period', ['loco_model_name'], unique=False)
    op.drop_index(op.f('ix_locomotive_repair_period_loco_model_name'), table_name='locomotive_repair_period')
    op.drop_table('locomotive_repair_period')
    # ### end Alembic commands ###
